
module.exports = {
    datas: [
        "http://www.mishequn.xyz/page/2/",
        "http://www.mishequn.xyz/page/3/",
        "http://www.mishequn.xyz/page/4/",
        "http://www.mishequn.xyz/page/5/",
        
        "http://hali.carenginehub.com/page/2/",
        "http://hali.carenginehub.com/page/3/",
        "http://hali.carenginehub.com/page/4/",
        "http://hali.carenginehub.com/page/5/",

        "http://hawishub.com/page/2/",
        "http://hawishub.com/page/3/",
        "http://hawishub.com/page/4/",
        "http://hawishub.com/page/5/",

        "http://maidys.xyz/page/2/",
        "http://maidys.xyz/page/3/",
        "http://maidys.xyz/page/4/",
        "http://maidys.xyz/page/5/",
        "http://maidys.xyz/page/2/",
        "http://maidys.xyz/page/3/",
        "http://maidys.xyz/page/4/",
        "http://maidys.xyz/page/5/",
        "http://maidys.xyz/page/2/",
        "http://maidys.xyz/page/3/",
        "http://maidys.xyz/page/4/",
        "http://maidys.xyz/page/5/",

        "http://hawishub.top/page/2/",
        "http://hawishub.top/page/3/",
        "http://hawishub.top/page/4/",
        "http://hawishub.top/page/5/",

        "http://www.tshciewe.xyz/page/2/",
        "http://www.tshciewe.xyz/page/3/",
        "http://www.tshciewe.xyz/page/4/",
        "http://www.tshciewe.xyz/page/5/",

        "http://maiygu.xyz/page/2/",
        "http://maiygu.xyz/page/3/",
        "http://maiygu.xyz/page/4/",
        "http://maiygu.xyz/page/5/",
        "http://maiygu.xyz/page/6/",
        "http://maiygu.xyz/page/7/",
        "http://maiygu.xyz/page/8/",
        "http://maiygu.xyz/page/9/",
        "http://maiygu.xyz/page/10/",
        "http://maiygu.xyz/page/11/",
        "http://maiygu.xyz/page/12/",

        "http://www.gouyaotuan.xyz/page/2/",
        "http://www.gouyaotuan.xyz/page/3/",
        "http://www.gouyaotuan.xyz/page/4/",
        "http://www.gouyaotuan.xyz/page/5/",

        'http://56ssc.cc/page/2/',
        'http://56ssc.cc/page/3/',
        'http://56ssc.cc/page/4/',
        'http://56ssc.cc/page/2/',
        'http://56ssc.cc/page/3/',
        'http://56ssc.cc/page/4/',
        'http://56ssc.cc/page/2/',
        'http://56ssc.cc/page/3/',
        'http://56ssc.cc/page/4/',
        'http://56ssc.cc/page/2/',
        'http://56ssc.cc/page/3/',
        'http://56ssc.cc/page/4/',
        'http://56ssc.cc/page/2/',
        'http://56ssc.cc/page/3/',
        'http://56ssc.cc/page/4/',
        'http://56ssc.cc/page/2/',
        'http://56ssc.cc/page/3/',
        'http://56ssc.cc/page/4/',
        'http://56ssc.cc/page/2/',
        'http://56ssc.cc/page/3/',
        'http://56ssc.cc/page/4/',
        'http://56ssc.cc/page/2/',
        'http://56ssc.cc/page/3/',
        'http://56ssc.cc/page/4/',
        'http://56ssc.cc/page/2/',
        'http://56ssc.cc/page/3/',
        'http://56ssc.cc/page/2/',
    ],
    selector: '.post-title'
}
